@startuml
title Data Pipeline
footer Disponível em https://github.com/acnaweb/mackenzie-2025-1

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
LAYOUT_LANDSCAPE()

Person(user, "Usuário")

System_Boundary(transacional, "Transacional"){
    Container(frontend, "Frontend", "Angular", "Web App de Interação")
    Container(api, "API", "Java")
    ContainerDb(db, "Database", "Oracle")
}   

    System_Boundary(olap, "OLAP"){
        Container(job, "Ingestão de Dados")
        ContainerDb(dw, "DataWarehouse", "BigQuery/Snowflake/Redshift/Exadata")
        Rel(job, dw, "Salvar dados da origem")
    }

Rel(user, frontend, "Realiza pedidos")
Rel(frontend, api, "Consome endpoints")
Rel(api, db, "Persiste dados")
Rel(db, job, "Carregar dados da Origem")

@enduml